// Client for the "Observed" channel -- DuckDuckGo Tracker Radar-derived
// data, captured independently of anything a site's privacy policy claims.
// See ../tracker_radar/README.md for how this data is produced.
//
// IMPORTANT (overclaiming guard -- read before changing how this is used):
// this is a *bundled snapshot*, not a live scan of the tab the popup is
// currently open on. tracker_radar/ works by launching a real headless
// Chromium via Playwright to capture third-party requests, which cannot
// run inside a browser-extension popup/content script. So
// `tracker_radar_snapshot.json` (this directory) is a point-in-time
// capture for a small curated list of sites (currently
// tracker_radar/config.SITES), regenerated by re-running
// `python3 -m tracker_radar.run` and copying the output here -- the same
// generated-artifact pattern as classifier/dist/redflags-engine.js (see
// classifier/README.md). Any UI built on lookupDomain()'s result must say
// something like "detected in a scan on <date>", never phrase it as
// real-time/continuous monitoring of the current page.
//
// Returns null for any domain not in the curated snapshot. Callers must
// render an explicit "not yet scanned" state for that case -- never
// silently omit the Observed section or imply a clean/passing result.
//
// `browserAPI` is declared once, in storage.js (loaded before this file in
// popup.html) -- these are classic <script> tags sharing one global scope.

const TRACKER_RADAR_SNAPSHOT_URL = "tracker_radar_snapshot.json";

let _trackerRadarSnapshotPromise = null;

function _loadTrackerRadarSnapshot() {
  if (!_trackerRadarSnapshotPromise) {
    _trackerRadarSnapshotPromise = fetch(browserAPI.runtime.getURL(TRACKER_RADAR_SNAPSHOT_URL))
      .then((resp) => {
        if (!resp.ok) throw new Error(`snapshot fetch failed (${resp.status})`);
        return resp.json();
      });
  }
  return _trackerRadarSnapshotPromise;
}

// Matches tosdr.js's bareDomain handling so "www.example.com" and
// "example.com" resolve to the same snapshot entry regardless of which
// form the current tab's hostname or the snapshot's `site` URL uses.
function _bareDomain(hostOrUrl) {
  let host = hostOrUrl;
  try {
    if (hostOrUrl.includes("://")) host = new URL(hostOrUrl).hostname;
  } catch {
    // not a parseable URL -- assume it's already a bare hostname
  }
  return host.replace(/^www\./, "").toLowerCase();
}

// Returns null if this domain isn't in the curated snapshot. Otherwise
// returns the full tracker_radar profile object (see tracker_radar/README.md
// "Output schema": trackerCount, topCategories, riskScore, flaggedOwners,
// coverage, etc.) plus { capturedAt, snapshotSource } so the UI can be
// explicit about when/how this was captured rather than implying "now".
async function lookupDomain(domain) {
  const snapshot = await _loadTrackerRadarSnapshot();
  const target = _bareDomain(domain);
  const match = (snapshot.entries || []).find((entry) => _bareDomain(entry.site) === target);
  if (!match) return null;
  return { ...match, capturedAt: snapshot.capturedAt, snapshotSource: snapshot.source };
}

window.TrackerRadarClient = { lookupDomain };
