# Generated by Django 5.2.15 on 2026-07-07 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('privacy_policy_url', models.URLField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('hash', models.CharField(db_index=True, max_length=64)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='tracker.website')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
